### ISSUE TITLE
browser scroll and resize issue

### ISSUE THREAD

**Issue by choiDoYoung** [AhmedAyachi/LeaderLine#1] opened 2023-06-27 07:06 UTC
There was an issue where the location was incorrectly updated when the browser was zoomed out after zooming out and scrolling, so it was fixed as follows.

```
position() {
      super.position()

      const { element, parent } = this
      const { style } = element; const { scrollLeft } = parent; const { left, top } = parent.getBoundingClientRect()
      style.transform = `translate(${-1 * (left - scrollLeft)}px,${-1 * (top + window.scrollY)}px)`
    }
```

**Comment by AhmedAyachi** [comment] 2023-06-27 07:49
@choiDoYoung I'll take a look at it and get back to you.
------- -------------
@choiDoYoung Tried to regenerate the unexpected behavior you're mentioning, but by zooming in/out after scrolling, things kept working as expected.
Please provide more information about the issue by clarifying the context in which the issue was produced and adding some attachments if possible. Thanks

**Comment by AhmedAyachi** [comment] 2023-08-01 17:36
I'm closing this issue since there was no reply from @choiDoYoung.

**Closed as completed by AhmedAyachi** 2023-08-01 17:36 UTC
